# Generated by Django 2.1.7 on 2019-03-17 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AMP', 'Amplifier'), ('CON', 'Controller'), ('SPK', 'Speaker'), ('CAT6TX', 'CAT6 Tx'), ('CAT6RX', 'CAT6 Rx'), ('LC', 'Lecture Capture'), ('TP', 'Touch Panel'), ('LCDMON', 'LCD Monitor')], max_length=50)),
                ('ins_ref', models.IntegerField()),
                ('fbs_ref', models.IntegerField()),
                ('serial_number', models.CharField(max_length=50)),
                ('mac_address', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Manufacturer'),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Location'),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.EquipmentModel'),
        ),
    ]
