# Generated by Django 2.1.7 on 2019-03-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20190322_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ins_ref',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
